indexing-settings:
  sites:
    - url: https://agrostroiservice.ru
      name: АгростройСервис
    - url: https://stomax.pro
      name: Стомакс
    - url: https://sazur.ru
      name: Сазур



spring.datasource.url: jdbc:postgresql://localhost:5433/graduate_work
spring.datasource.username: USER
spring.datasource.password: 12341990
spring.datasource.driver-class-name: org.postgresql.Driver
connectionProperties: useUnicode=true;characterEncoding=utf8;
spring.sql.init.mode: always

spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true
